/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Gestor;
import Modelo.Vinculo;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prophet
 */
public class AdministrarVinculos extends javax.swing.JInternalFrame {

   
    ArrayList<Vinculo> listado;
    Gestor g;
    String parametroFecha;
    public AdministrarVinculos() {
        initComponents();
        g = new Gestor();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnFiltrar = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        lblPruebaFecha = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Editar vinculos entre productos y proveedores");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Filtrar relaciones por fecha");

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        btnFiltrar.setText("Buscar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        jDateChooser2.setDateFormatString("dd/MM/yyyy");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPruebaFecha.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addGap(31, 31, 31)
                                        .addComponent(lblPruebaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(lblPruebaFecha)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        //buscar vinculos por fecha
        try
        {
            Date fecha = jDateChooser1.getDate();
            DateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            parametroFecha = f.format(fecha);
            cargarTabla(parametroFecha);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Campo fecha vacio o datos de entrada incorrectos","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
            
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Date fecha = jDateChooser2.getDate();
        DateFormat f = new SimpleDateFormat("yyyyMMdd");
        parametroFecha = f.format(fecha);
        lblPruebaFecha.setText(parametroFecha);
    }//GEN-LAST:event_jButton1ActionPerformed

   
    private void cargarTabla(String fecha)
    {
        try 
        {       DefaultTableModel dtm = new DefaultTableModel();
                listado = g.getListadoVinculosPorFecha(fecha);
                dtm.setColumnIdentifiers(new String[]{"COD PRODUCTO","PRODUCTO","COD PROVEEDOR","PROVEEDOR","HORA ALTA"});
                for (Vinculo vin : listado) {
                Vector v = new Vector();
                v.add(vin.getCodigoProducto());
                v.add(vin.getProducto());
                v.add(vin.getCodigoProveedor());
                v.add(vin.getProveedor());
                v.add(vin.getHoraAlta());
                dtm.addRow(v);
                }
                jTable1.setModel(dtm);
                filasNoEditables(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarStock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void filasNoEditables(JTable tabla)
    {
         for (int c = 0; c < tabla.getColumnCount(); c++)
            {
                Class<?> col_class = tabla.getColumnClass(c);
                tabla.setDefaultEditor(col_class, null);        // remover editor
            }
    }

    
    private void inicio()
    {
        jTable1.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent Mouse_evt) {
        JTable table =(JTable) Mouse_evt.getSource();
        Point point = Mouse_evt.getPoint();
        int row = table.rowAtPoint(point);
        if (Mouse_evt.getClickCount() == 2) 
        {
              
           try 
           {
                /*
                int codigoProducto = Integer.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                String producto = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
                int codigoProveedor = Integer.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
                String proveedor = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
                */
                String horaAlta = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString().trim();
                String mensaje="";
                if (JOptionPane.showConfirmDialog(rootPane, "Se eliminara el vínculo creado el dia,"+ parametroFecha+" a las "+horaAlta+""
                        + " ¿desea continuar?",
                "Deshacer vínculos", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                {
                    try 
                    {
                        mensaje = g.eliminarVinculo(parametroFecha, horaAlta);
                        JOptionPane.showMessageDialog(null,mensaje,"Error",JOptionPane.INFORMATION_MESSAGE);
                        cargarTabla(parametroFecha);              
                    } 
                    catch (SQLException ex) 
                    {
                        JOptionPane.showMessageDialog(null, ex.toString()+","+mensaje,"Error",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
           } 
           catch (HeadlessException | NumberFormatException e) 
           {
                JOptionPane.showMessageDialog(null, "Debe ingresar un valor numérico", "Información", JOptionPane.INFORMATION_MESSAGE);            
           }
            
        }
        
        
        }
        });
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPruebaFecha;
    // End of variables declaration//GEN-END:variables
}
