
package Vistas;

import Controlador.Gestor;
import Dto.VentaDTO;
import Modelo.CellRenderer;
import Modelo.HeaderCellRenderer;
import Modelo.Ventana;
import static Vistas.Main.panelEscritorio;
import com.orsonpdf.PDFDocument;
import com.orsonpdf.PDFGraphics2D;
import com.orsonpdf.Page;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.title.LegendTitle;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.ui.HorizontalAlignment;
import org.jfree.ui.RectangleEdge;


public class FiltroVentasEntreFechas extends javax.swing.JInternalFrame {

    Gestor g;
    private String fechaInicio;
    private String fechaFinal;
    private String fIni;
    private String fFin;
    private static String f1;
    private static String f2;
    private static double pTarjeta;
    private static double pDebito;
    private static double pTransf;
    private static double pEfectivo;
    private TableRowSorter trsfiltro;
    String filtro;
    int c;
    double porcTarjeta=0.0;
    double porcEfectivo=0.0;
    double porcDebito=0.0;
    double porcTrans=0.0;
    public FiltroVentasEntreFechas() {
        initComponents();
        g = new Gestor();
        txtDniCliente.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtDniCliente.getText().toUpperCase());
                txtDniCliente.setText(cadena);
                repaint();
                filtro();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        fechaHasta = new com.toedter.calendar.JDateChooser();
        btnFiltro = new javax.swing.JButton();
        lblCantidadFilas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCantArtVendidos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setTitle("Filtrar  ventas realizadas entre fechas");

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVentas);

        jLabel1.setText("FILTRAR VENTAS POR FECHA     ENTRE EL:");

        fechaDesde.setDateFormatString("dd/MM/yyyy");

        jLabel2.setText("Y EL:");

        fechaHasta.setDateFormatString("dd/MM/yyyy");

        btnFiltro.setText("Filtrar");
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        lblCantidadFilas.setText("...");

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("CANTIDAD DE VENTAS:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("TOTAL DE ARTICULOS VENDIDOS:");

        lblCantArtVendidos.setText("...");

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("MONTO TOTAL:");

        lblMonto.setText("...");

        jLabel3.setText("REFINAR POR DNI CLIENTE:");

        txtDniCliente.setEnabled(false);
        txtDniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniClienteKeyTyped(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Graficar formas de pago");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("PDF");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(lblCantidadFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(lblCantArtVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(40, 40, 40)
                        .addComponent(lblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnFiltro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCantidadFilas)
                    .addComponent(jLabel5)
                    .addComponent(lblCantArtVendidos)
                    .addComponent(jLabel6)
                    .addComponent(lblMonto))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     
    
    public void filtro() 
    {
        filtro = txtDniCliente.getText();
        trsfiltro.setRowFilter(RowFilter.regexFilter(txtDniCliente.getText(), 5));
        calculos();
    }
    
    
    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        // Aplicar filtro para busqueda de ventas
        
        Date fechaIni = this.fechaDesde.getDate();
        Date fechaFin = this.fechaHasta.getDate();
        DateFormat f = new SimpleDateFormat("yyyyMMdd");
        DateFormat ff = new SimpleDateFormat("dd-MM-yyyy");
        fIni = ff.format(fechaIni);
        fFin = ff.format(fechaFin);
        fechaInicio = f.format(fechaIni);
        fechaFinal = f.format(fechaFin);
        f1=fIni;
        f2=fFin;
        try
        {
            cargarTabla();
            calculos();
            txtDniCliente.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage(),"Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnFiltroActionPerformed
  
    private void txtDniClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniClienteKeyTyped
        
        char c=evt.getKeyChar();
	if(Character.isLetter(c)) 
        {
		getToolkit().beep();
		evt.consume();
        }
        trsfiltro = new TableRowSorter(tablaVentas.getModel());
        tablaVentas.setRowSorter(trsfiltro);   
    }//GEN-LAST:event_txtDniClienteKeyTyped

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        FiltroVentasEntreFechas nuevo = new FiltroVentasEntreFechas();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ventana nueva = new  Ventana(porcEfectivo, porcTrans, porcDebito, porcTarjeta,fIni,fFin);
        nueva.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // emite e documento en pdf en la ubicación especificada
        
        emitirArchivoPDF();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    void CentrarVentana(JInternalFrame frame) {
        panelEscritorio.add(frame);
        Dimension dim = panelEscritorio.getSize();
        Dimension framesise = frame.getSize();
        frame.setLocation((dim.width - framesise.width) / 2, (dim.height - framesise.height) / 2);
        frame.show();
    }
    
    
    private void calculos()
    {
        int cantidadAcumulada=0;
        int cantidadDebito=0;
        int cantidadTranf=0;
        int cantidadTarjeta=0;
        int cantidadEfectivo=0;
       
        double monto =0;
        for (int i = 0; i < tablaVentas.getRowCount(); i++) 
        {
            cantidadAcumulada += Integer.valueOf(tablaVentas.getValueAt(i, 6).toString());
            monto += Double.valueOf(tablaVentas.getValueAt(i, 7).toString().replace("$", "").trim());
            if(tablaVentas.getValueAt(i, 3).toString().contains("Tarjeta"))
            {
                cantidadTarjeta++;
            }
            if(tablaVentas.getValueAt(i, 3).toString().contains("Efectivo"))
            {
                cantidadEfectivo++;
            }
            if(tablaVentas.getValueAt(i, 3).toString().contains("Transferencia"))
            {
                cantidadTranf++;
            }
            if(tablaVentas.getValueAt(i, 3).toString().contains("Débito"))
            {
                cantidadDebito++;
            }
            
            
      
            
        }
        //5*100/10  parcial*100/parcial
        DecimalFormat f = new DecimalFormat("###,###.##");
        porcTarjeta = (cantidadTarjeta * 100) / c;
        porcEfectivo = (cantidadEfectivo * 100) / c;
        porcDebito = (cantidadDebito * 100) / c;
        porcTrans = (cantidadTranf * 100) / c;
        lblCantArtVendidos.setText(String.valueOf(cantidadAcumulada));
        lblMonto.setText("$"+String.valueOf(f.format(monto)));
        pTarjeta=porcTarjeta;
        pDebito=porcDebito;
        pTransf=porcTrans;
        pEfectivo=porcEfectivo;
    }
    
    private void cargarTabla() {

        try {

            ArrayList<VentaDTO> listado = new ArrayList();
            
            DefaultTableModel modelo = new DefaultTableModel();
            listado = g.getVentasFilroFechas(fechaInicio,fechaFinal);
            modelo.setColumnIdentifiers(new String[]{"Nro venta","Fecha","Hora","Forma de pago","Vendedor","Cliente Nro","Cant. art. vendida","Monto"});
            for (VentaDTO vta : listado) {
                Vector v = new Vector();
                v.add(vta.getNroVenta());
                v.add(vta.getFecha());
                v.add(vta.getHora());
                v.add(vta.getFormaPago());
                v.add(vta.getOperador());
                v.add(vta.getDni());
                v.add(vta.getCantVendida());
                v.add("$"+vta.getMontoTotal());
                modelo.addRow(v);
            }

            tablaVentas.setModel(modelo);
            //color de los bordes de las celdas
            c =tablaVentas.getRowCount();
            lblCantidadFilas.setText(String.valueOf(c));
            tablaVentas.setGridColor(new java.awt.Color(214, 213, 208));
            //tamaño de columnas
            tablaVentas.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaVentas.getColumnModel().getColumn(4).setPreferredWidth(90);
            tablaVentas.getColumnModel().getColumn(0).setPreferredWidth(60);
            //altura de filas
            tablaVentas.setRowHeight(24);
            //se asigna el nuevo CellRenderer a cada columna segun su contenido
            tablaVentas.getColumnModel().getColumn(0).setCellRenderer(new CellRenderer("minimo"));
            tablaVentas.getColumnModel().getColumn(5).setCellRenderer(new CellRenderer("minimo"));
            tablaVentas.getColumnModel().getColumn(2).setCellRenderer(new CellRenderer("hour"));
            tablaVentas.getColumnModel().getColumn(3).setCellRenderer(new CellRenderer("text"));
            tablaVentas.getColumnModel().getColumn(4).setCellRenderer(new CellRenderer("text"));
            tablaVentas.getColumnModel().getColumn(6).setCellRenderer(new CellRenderer("num"));
            tablaVentas.getColumnModel().getColumn(7).setCellRenderer(new CellRenderer("moneda"));
            //Se asigna nuevo header a la tabla
            JTableHeader jtableHeader = tablaVentas.getTableHeader();
            jtableHeader.setDefaultRenderer(new HeaderCellRenderer());
            tablaVentas.setTableHeader(jtableHeader);
           
        } catch (Exception e) {

        }
    }
    
    
    
    private void emitirArchivoPDF()
    {
        JFreeChart chart = createChart(createDataset());
        
        PDFDocument pdfDoc = new PDFDocument();
        pdfDoc.setTitle("Reporte Drone Store");
        pdfDoc.setAuthor("lucia de Leonardis");
        
        Page page = pdfDoc.createPage(new Rectangle(612, 800));    
        PDFGraphics2D g2 = page.getGraphics2D();

        chart.draw(g2, new Rectangle(0, 0, 612, 800));       
        pdfDoc.writeToFile(new File("C:\\InformesDroneStore\\DroneStore.pdf"));
        
        
        System.out.println("archivo pdf generado correctamente...");
    }
    
    
    
    private static PieDataset createDataset() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        if(pTarjeta>0.0)
        {
            dataset.setValue("Tarjeta de crédito", pTarjeta);
        }
        if(pDebito>0.0)
        {
            dataset.setValue("Débito", pDebito);
        }
        if(pTransf>0.0)
        {
            dataset.setValue("Transferencia", pTransf);
        }
        if(pEfectivo>0.0)
        {
            dataset.setValue("Efectivo", pEfectivo);
        }

        return dataset;
    }

    public static JFreeChart createChart(PieDataset dataset) {

        JFreeChart chart = ChartFactory.createPieChart(
                "INFORME DE VENTAS Y FORMAS DE PAGO", dataset, false, false, false);

        chart.setBackgroundPaint(new GradientPaint(new Point(0, 0),
                new Color(20, 20, 20), new Point(400, 200), Color.LIGHT_GRAY));

        TextTitle t = chart.getTitle();
        t.setHorizontalAlignment(HorizontalAlignment.CENTER);
        t.setPaint(new Color(240, 240, 240));
        t.setFont(new Font("Arial", Font.BOLD, 26));

        PiePlot plot = (PiePlot) chart.getPlot();

        
        plot.setBackgroundPaint(null);
        plot.setInteriorGap(0.04);
        plot.setOutlineVisible(false);
        plot.setShadowPaint(null);
        plot.setLabelShadowPaint(null);
        plot.setBaseSectionOutlinePaint(Color.WHITE);
        plot.setSectionOutlinesVisible(true);
        plot.setBaseSectionOutlineStroke(new BasicStroke(2.0f));
        plot.setLabelFont(new Font("Courier New", Font.BOLD, 20));
        plot.setLabelLinkPaint(Color.WHITE);
        plot.setLabelLinkStroke(new BasicStroke(2.0f));
        plot.setLabelOutlineStroke(null);
        plot.setLabelPaint(Color.WHITE);
        plot.setLabelBackgroundPaint(null);

        TextTitle url = new TextTitle(
                "Web: http://dronestore.com",
                new Font("Courier New", Font.PLAIN, 12));
        url.setPaint(Color.BLUE);
        url.setPosition(RectangleEdge.BOTTOM);
        url.setHorizontalAlignment(HorizontalAlignment.RIGHT);

        TextTitle description = new TextTitle(
                "Reporte de ventas entre las fechas "+f1+ " y el " +f2 ,
                new Font("Arial", Font.PLAIN, 18));
        description.setPaint(Color.DARK_GRAY);
        description.setPosition(RectangleEdge.TOP);
        description.setHorizontalAlignment(HorizontalAlignment.CENTER);


        chart.addSubtitle(description);
        chart.addSubtitle(url);

        return chart;
    }
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltro;
    private com.toedter.calendar.JDateChooser fechaDesde;
    private com.toedter.calendar.JDateChooser fechaHasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantArtVendidos;
    private javax.swing.JLabel lblCantidadFilas;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtDniCliente;
    // End of variables declaration//GEN-END:variables
}
