/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Gestor;
import Dto.ProductoDTO;
import Modelo.ProductoPorProveedor;
import Modelo.Proveedor;
import static Vistas.Main.panelEscritorio;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Prophet
 */
public class VincularProductosProveedor extends javax.swing.JInternalFrame {

    ArrayList<Proveedor> listaProveedores;
    ArrayList<ProductoDTO> listadoProductos;
    Gestor g;
    boolean param1,param2;
    ProductoPorProveedor nuevo;
    Proveedor miProveedor;
    ProductoDTO miProducto;
    public VincularProductosProveedor() {
        initComponents();
        this.setTitle("Vincular producto con proveedor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnVincular = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBuscarProveedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCodigoProveedor = new javax.swing.JLabel();
        lblDetalleProveedor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDescProducto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCodigoProducto = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        jLabel7.setText("Establecer precio para el proveedor");

        txtPrecio.setEnabled(false);

        btnVincular.setText("Vincular y establecer precio");
        btnVincular.setEnabled(false);
        btnVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVincularActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscarProveedor.setText("Buscar Proveedor");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Detalle proveedor:");

        jLabel3.setText("Código de proveedor");

        lblCodigoProveedor.setForeground(new java.awt.Color(255, 51, 51));
        lblCodigoProveedor.setText("...");

        lblDetalleProveedor.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarProveedor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDetalleProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCodigoProveedor))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDetalleProveedor))
                .addGap(50, 50, 50)
                .addComponent(btnBuscarProveedor)
                .addGap(47, 47, 47))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDescProducto.setText("...");

        jLabel1.setText("Código de producto:");

        lblCodigoProducto.setForeground(new java.awt.Color(255, 51, 51));
        lblCodigoProducto.setText("...");

        btnBuscarProducto.setText("Buscar Producto");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jLabel2.setText("Detalle producto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(lblCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarProducto)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(lblDescProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCodigoProducto))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDescProducto))
                .addGap(51, 51, 51)
                .addComponent(btnBuscarProducto)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_Exit_32.png"))); // NOI18N
        btnSalir.setText("Salir ");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio)
                    .addComponent(btnVincular, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnVincular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVincularActionPerformed
        // vincular y establecer precio del producto para el proveedor
        if(!txtPrecio.getText().isEmpty())
        {
            nuevo = new ProductoPorProveedor();
            nuevo.setCodigoProducto(miProducto.getCodigoProducto());
            nuevo.setCodigoProveedor(miProveedor.getCodigo());
            nuevo.setPrecio(Double.valueOf(txtPrecio.getText()));
            if (JOptionPane.showConfirmDialog(rootPane, "Se va a vincular el producto código:"+nuevo.getCodigoProducto()+", con el proveedor nro:"+nuevo.getCodigoProveedor()+" ¿desea continuar?",
                "Abandonar", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                try 
                {
                    String mensaje = g.setProductoPorProveedorPrecio(nuevo);
                    JOptionPane.showMessageDialog(this,mensaje,"Operación",JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    VincularProductosProveedor v = new  VincularProductosProveedor();
                    CentrarVentana(v);
                } 
                catch (SQLException ex) 
                {
                    JOptionPane.showMessageDialog(this,ex.getMessage()+" El producto ya se encuentra vinculado.","Aviso de error",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"El campo precio no debe estar vacio.","Aviso de error",JOptionPane.INFORMATION_MESSAGE);
            txtPrecio.grabFocus();
        }
    }//GEN-LAST:event_btnVincularActionPerformed

    
     void CentrarVentana(JInternalFrame frame) {
        panelEscritorio.add(frame);
        Dimension dim = panelEscritorio.getSize();
        Dimension framesise = frame.getSize();
        frame.setLocation((dim.width - framesise.width) / 2, (dim.height - framesise.height) / 2);
        frame.show();
    }
    
    
    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        // buscar proveedor
        
        
        miProveedor = new Proveedor();
       
        miProveedor=buscarProveedor(Integer.parseInt(JOptionPane.showInputDialog("INGRESE EL COD DE PROVEEDOR")));
        if(miProveedor.getCodigo()==0)
        { 
            JOptionPane.showMessageDialog(this,"El código de  proveedor no existe.","Aviso de error",JOptionPane.INFORMATION_MESSAGE);
            lblCodigoProveedor.setText("");
            lblDetalleProveedor.setText("");
        }
        else
        {
           lblCodigoProveedor.setText(String.valueOf(miProveedor.getCodigo()));
           lblDetalleProveedor.setText(miProveedor.getDescripcion());
        }
        
        validar(param1, param2);
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // buscar producto
        miProducto = new ProductoDTO();
        miProducto=buscarProducto(Integer.parseInt(JOptionPane.showInputDialog("INGRESE EL COD DE PRODUCTO")));
        if(miProducto.getCodigoProducto()==0)
        {
            JOptionPane.showMessageDialog(this,"El código del producto no existe.","Aviso de error",JOptionPane.INFORMATION_MESSAGE);    
            lblCodigoProducto.setText("");
            lblDescProducto.setText("");
        }
        else
        {
            lblCodigoProducto.setText(String.valueOf(miProducto.getCodigoProducto()));
            lblDescProducto.setText(miProducto.getDescripcion());
        }
        validar(param1, param2);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Salir
        if (JOptionPane.showConfirmDialog(rootPane, "Se cerrara la ventana, ¿desea continuar?",
        "Abandonar", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private ProductoDTO buscarProducto(int codigo)
    {
        g= new Gestor();
        ProductoDTO p = new ProductoDTO();
        try {
            listadoProductos = g.getListadoProductos();
            for (ProductoDTO pr : listadoProductos) {
                if(pr.getCodigoProducto()==codigo)
                {
                    p=pr;
                    param1=true;
                    break;
                }
                else
                {
                    param1=false;
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VincularProductosProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return p;
    }
    
    
    private Proveedor buscarProveedor(int codigo)
    {
        g = new Gestor();
        Proveedor p = new Proveedor();
        listaProveedores = g.getListadoProveedores();
        for (Proveedor pr : listaProveedores) {
            if(pr.getCodigo()==codigo)
            {
                p=pr;
                param2=true;
                break;
            }
            else
            {
                param2=false;
            }
        }
        
        return p;
    }
    
    private void validar(boolean param1,boolean param2)
    {
        
        if(param1 && param2)
        {
            txtPrecio.setEnabled(true);
            btnVincular.setEnabled(true);
        }
        else
        {
            txtPrecio.setEnabled(false);
            btnVincular.setEnabled(false);
        }
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVincular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblCodigoProveedor;
    private javax.swing.JLabel lblDescProducto;
    private javax.swing.JLabel lblDetalleProveedor;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
